# Configuração básica do Jekyll
title: Inteligência Artificial
description: Documentação sobre IA usando o Zendesk Garden Jekyll Theme
baseurl: "" # Deixe vazio para GitHub Pages no nível raiz
url: "https://pehenobra2.github.io/PortifoliosIA/"

# Tema do Zendesk Garden
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

# Ativar navegação lateral
sidebar:
  - title: "Índice"
    nav:
      - "docs/introducao"
      - "docs/algoritmos-geneticos"
      - "docs/aplicacoes-geneticos"

# Configuração de coleções (se necessário)
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "single"

# Outros plugins necessários
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
