# Configuração básica do Jekyll
title: Inteligência Artificial
description: Documentação sobre IA usando o Zendesk Garden Jekyll Theme
baseurl: "" # Deixe vazio para GitHub Pages no nível raiz
url: "https://pehenobra2.github.io/PortifoliosIA/"
theme: jekyll-theme-minimal

# Sidebar
sidebar:
  - label: "Portfólio 1"
    children:
      - "portifolio1/video"
  - label: "Portfólio 2"
    children:
      - "portiolio2/ImpressoesIniciais"
      - "portiolio2/subtopicos"
      - "portiolio2/discussoes"
      - "portiolio2/projetosEproblemas"
      - "portiolio2/conclusao"
      - "portiolio2/referencias"
      
# Configuração de navegação
plugins:
  - jekyll-titles-from-headings # Gera títulos automaticamente a partir dos cabeçalhos
