# Configuração básica do Jekyll
title: Inteligência Artificial
description: Documentação sobre IA usando o Zendesk Garden Jekyll Theme
baseurl: "" # Deixe vazio para GitHub Pages no nível raiz
url: "https://pehenobra2.github.io/PortifoliosIA/"
theme: jekyll-theme-minimal
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

# Sidebar
sidebar:
  - label: "Portfólio 1"
    children:
      - video
  - label: "Portfólio 2"
    children:
      - impressoes-iniciais
      - subtopicos
      - discussoes
      - projetosEproblemas
      - conclusao
      - referencias

      
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Outras configurações
verbose: true
